name: Keep SmartCash AI Awake
on:
  schedule:
    - cron: '0 */10 * * *' # Runs every 10 hours
  workflow_dispatch:      # Allows you to trigger it manually

jobs:
  keep_awake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Empty Commit
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit --allow-empty -m "Automated Heartbeat to prevent hibernation"
          git push
